<?php

namespace DMS\Bundle\LauncherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreUserRepository extends EntityRepository
{
    public function getReferralsCount($token)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->addSelect('COUNT(u.id)');
        $qb->andWhere('u.referrerToken = ?0');
        $qb->setParameter(0, $token);

        $qb->groupBy('u.referrerToken');

        $result = $qb->getQuery()->getSingleResult();

        return (is_array($result))? $result[1]:0;
    }

}