services:
    dms.filter:
        class: DMS\Bundles\FilterBundle\Service\Filter

    dms.filter.type_extension:
        class: DMS\Bundles\FilterBundle\Form\Type\FormTypeFilterExtension
        arguments:
            filter: @dms.filter
            auto_filter: %dms_filter.auto_filter_forms%
        tags:
            - { name: form.type_extension, alias: form }
